spring:
  application:
    name: demo-front-service

  main:
    banner-mode: off

management:
  endpoints:
    jmx:
      exposure:
        exclude: '*'
    web:
      exposure:
        include: health, metrics, prometheus

springdoc:
  api-docs:
    path: '/api-docs'
  swagger-ui:
    path: '/api-docs/swagger-ui.html'


server:
  port: 8080
  servlet:
    context-path: '/demo-front'
